from numpy import mod
import pylab
from re import sub
import matplotlib as mpl
from .colors import rgb2hex, fColrs

# Should be placed in some kind of InitClear
mpl.rcParams['lines.linewidth'] = 1.55
mpl.rcParams['font.size'] = 15
mpl.rcParams['axes.color_cycle']=[rgb2hex(c) for c in fColrs()]

# mpl.rcParams['font.family'] = 'helvetica'
# line.set_dashes([8, 4, 2, 4, 2, 4]) 
#lg = a.legend()
# fr = lg.get_frame()
# fr.set_lw(0.2)
#
# --------------------------------------------------------------------------------
# --- Export parameters 
# --------------------------------------------------------------------------------
class FigureExportParams:
    def __init__(self):
        self.path=['./']
        self.width=None
        self.height=None
        self.title=None
        self.btitle=False
        self.blatex=False
        self.bconstrained=False

_global_params = FigureExportParams()  

def setFigureWidth(width):
    _global_params.width=width

def setFigureHeigth(height):
    _global_params.height=height

def setFigurePath(path):
    if type(path)==list:
        _global_params.path=path
    else:
        _global_params.path=[path]

def setFigureTitle(btitle):
    _global_params.btitle=btitle


# --------------------------------------------------------------------------------
# --- Some Tools
# --------------------------------------------------------------------------------
def title2filename(title):
  return sub(r'[%|:;.\[ \]\\=^*_/]','',title)

# --------------------------------------------------------------------------------
# --- Exporter 
# --------------------------------------------------------------------------------

class FigureExporter:

    @staticmethod
    def print1figure(figName,titleLatexSafe,script_name,script_run_dir,script_run_date):
            print('in \\autoref{fig:%s}',figName);
            print('% ---------------------------------- FIGURE --------------------------------------')
            print('%% Figure generated by script: %s, from folder: %s, %s'%(script_name,script_run_dir,script_run_date));
            print('\\noindent\\begin{figure}[!htbp]\\centering%%');
            print('  \\includegraphics[width=0.49\\textwidth]{%s}'%figName);
            print('  \\caption{%s}\\label{fig:%s}%%'%(titleLatexSafe,figName));
            print('\\end{figure}');
            print('% --------------------------------------------------------------------------------')
            print(' ')

    @staticmethod
    def print2figures(figName,figNameLast,titleLatexSafe,script_name,script_run_dir,script_run_date):
            print('in \\autoref{fig:%sMain}'%figNameLast);
            print('% ---------------------------------- FIGURES -------------------------------------')
            print('%% Figure generated by script: %s, from folder: %s, %s'%(script_name,script_run_dir,script_run_date));
            print('%% subfig a:  in \\autoref{fig:%s}'%figNameLast);
            print('%% subfig b:  in \\autoref{fig:%s}'%figName);
            print('\\noindent\\begin{figure}[!htbp]\\centering%%');
            print('  \\begin{subfigure}[b]{0.49\\textwidth}\\centering \\includegraphics[width=\\textwidth]{%s}\\caption{}\\label{fig:%s}\\end{subfigure}%%'%(figNameLast,figNameLast));
            print('  \\begin{subfigure}[b]{0.49\\textwidth}\\centering \\includegraphics[width=\\textwidth]{%s}\\caption{}\\label{fig:%s}\\end{subfigure}%%'%(figName,figName));
            print('  \\caption{%s}\\label{fig:%sMain}%%'%(titleLatexSafe,figNameLast));
            print('\\end{figure}');
            print('% --------------------------------------------------------------------------------')
            print(' ')
    @staticmethod
    def export(fig,figformat,i=1,n=1,width=None,height=None,figNameLast='',script_name='',script_run_dir='',script_run_date=''):
        # params (for now, using global params)
        params=_global_params

        ax=fig.gca()
        # storing the title, figure name
        title=ax.get_title()
        titleLatexSafe = sub(r"[_%^]", "", title)
        # figure name from title or figure number
        if title=='' or (title is None):
            figName='%d'%i
        else:
            figName=title2filename(title);



        # remove figure title if needed
        if not params.btitle:
            ax.set_title('')
        
        if params.blatex :
            pass
#             for iax =1:length(axList)
#                 ax=axList(iax);
#                 format_ticks(ax,0.02,0.009,'FontSize',11); % font size useless, hgexport takes care of it

        if params.bconstrained:
            pass
        # Actually just using the loose figure is enough to keep what the user has inputted it seems
            #xlims=get(gca,'XLim');
            #ylims=get(gca,'YLim');
            #pause(1)
            #set(gca,'XLim',xlims);
            #set(gca,'YLim',ylims);

        # --------------------------------------------------------------------------------
        # --- Exporting in figure pathc
        # --------------------------------------------------------------------------------
        print(params.path)
        for ifp in range(len(params.path)):
            filename='%s%s.%s'%(params.path[ifp],figName,figformat);
            fig.savefig(filename)
            print('Exporting:%s'%filename)
            # restoring the title
            ax.set_title(title)


        # --------------------------------------------------------------------------------
        # --- Generating latex code 
        # --------------------------------------------------------------------------------
        if mod(n,2)==0:
            if mod(i,2)==0:
                FigureExporter.print2figures(figName,figNameLast,titleLatexSafe,script_name,script_run_dir,script_run_date)
        else:
            if mod(i,2)==0:
                FigureExporter.print2figures(figName,figNameLast,titleLatexSafe,script_name,script_run_dir,script_run_date)
            else:
                if i==n:
                    FigureExporter.print1figure(figName,titleLatexSafe,script_name,script_run_dir,script_run_date)

        figNameLast=figName;
        return figNameLast


__exporter = FigureExporter()  


# --------------------------------------------------------------------------------
# --- Export call wrapper 
# --------------------------------------------------------------------------------
def export(figformat,fig=None,i=None,width=None,height=None):
    if fig is None:
        # We'll loop over all figures
        figures=[manager.canvas.figure for manager in pylab.matplotlib._pylab_helpers.Gcf.get_all_fig_managers()]
        figNameLast=''
        for i, figure in enumerate(figures):
            figNameLast=__exporter.export(fig=figure,figformat=figformat,i=(i+1),n=len(figures),width=width,height=height,figNameLast=figNameLast)

    else:
        __exporter.export(fig=fig,figformat=figformat,i=i,width=width,height=height)
        pass
    
    for ifp in range(len(_global_params.path)):
        print('Figure saved in: %s'%_global_params.path[ifp]);
    print(' ');

    pass

def export2pdf(fig=None,i=None,width=None,height=None):
    export('pdf',fig=fig,i=i,width=width,height=height)
def export2png(fig=None,i=None,width=None,height=None):
    export('png',fig=fig,i=i,width=width,height=height)
def export2eps(fig=None,i=None,width=None,height=None):
    export('png',fig=fig,i=i,width=width,height=height)


# --------------------------------------------------------------------------------
# --- Example/test 
# --------------------------------------------------------------------------------
def test_export():

    #from ebra.export import *
    from numpy import linspace,sin,pi
    from matplotlib import pyplot as plt
    setFigurePath('./')

    x=linspace(0,2*pi,100);
    plt.figure()
    plt.title('fig_python')
    plt.grid()
    plt.plot(x,sin(x),'-')
    plt.xlabel('x coordinate [m]')
    plt.ylabel('Velocity  U_i [m/s]')
    plt.xlim([0,2*pi])

    export2pdf()

if __name__ == "__main__":
    test_export()
